{
 "title": "yams-dav-syncher",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "JOB", "query": "${VAR_JOB}" },
   {
    "name": "PERIOD",
    "label": "Period",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Open file descriptors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": " process_open_fds{job=\"$JOB\"}/process_max_fds{job=\"$JOB\"}"
    },
    {}
   ]
  },
  {
   "title": "Sent images",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "yams_sent_images_total{job=\"$JOB\"}"
    }
   ]
  },
  {
   "title": "Processed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "yams_processed_images_total{job=\"$JOB\"}"
    }
   ]
  },
  {
   "title": "Synchronization Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yams_sent_images_total{job=\"$JOB\"}",
     "legendFormat": "Sent"
    },
    {
     "expr": "yams_skipped_images_total{job=\"$JOB\"}",
     "legendFormat": "Skipped"
    },
    {
     "expr": "yams_recovered_images_total{job=\"$JOB\"}",
     "legendFormat": "Recovered"
    },
    {
     "expr": "yams_failure_images_total{job=\"$JOB\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "yams_duplicated_images_total{job=\"$JOB\"}",
     "legendFormat": "Duplicated"
    }
   ]
  },
  {
   "title": "Progress",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "repeat": "JOB",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "yams_processed_images_total{job=\"$JOB\"}/yams_images_total{job=\"$JOB\"} "
    },
    {}
   ]
  },
  {
   "title": "CPU time spent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"$JOB\"}",
     "legendFormat": "CPU time spent"
    }
   ]
  },
  {
   "title": "Max open file desc",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_max_fds{job=\"$JOB\"}"
    },
    {}
   ]
  },
  {
   "title": "Recovered",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "yams_recovered_images_total{job=\"$JOB\"}"
    }
   ]
  },
  {
   "title": "Estimated End In",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 4 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "(yams_images_total{job=\"$JOB\"}-yams_processed_images_total{job=\"$JOB\"})/delta(yams_processed_images_total{job=\"$JOB\"}[1m])",
     "legendFormat": "Remains"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": " process_open_fds{job=\"$JOB\"}"
    },
    {}
   ]
  },
  {
   "title": "Total to be sent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "yams_images_total{job=\"$JOB\"}"
    }
   ]
  },
  {
   "title": "Skipped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "yams_skipped_images_total{job=\"$JOB\"}"
    }
   ]
  },
  {
   "title": "Sent Per $PERIOD",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(yams_sent_images_total{job=\"$JOB\"}[$PERIOD])"
    }
   ]
  },
  {
   "title": "Not found",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "yams_not_found_images_total{job=\"$JOB\"}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "yams_failed_images_total{job=\"$JOB\"}"
    }
   ]
  },
  {
   "title": "Conflictive Names",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "yams_conflictive_name_total{job=\"$JOB\"}"
    }
   ]
  },
  {
   "title": "Conflictive Names",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "yams_upload_duplicated_error_total{job=\"$JOB\"}"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"$JOB\"}",
     "legendFormat": "Open File Descriptors"
    }
   ]
  },
  {
   "title": "Memory stats",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$JOB\"}",
     "legendFormat": "Resident used"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"$JOB\"}",
     "legendFormat": "Virtual memory used"
    },
    {
     "expr": "go_memstats_sys_bytes{job=\"$JOB\"}",
     "legendFormat": "Sys memory"
    },
    { "legendFormat": "Mem cache in use" }
   ]
  },
  {
   "title": "Processed images per $PERIOD",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(yams_processed_images_total{job=\"$JOB\"}[$PERIOD])",
     "legendFormat": "Processed"
    }
   ]
  },
  {
   "title": "Allocated bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$JOB\"}",
     "legendFormat": "bytes allocated and still in use"
    }
   ]
  },
  {
   "title": "Not found per  $PERIOD",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(yams_not_found_images_total{job=\"$JOB\"}[$PERIOD])",
     "legendFormat": "Processed"
    }
   ]
  },
  {
   "title": "Failed per  $PERIOD",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(yams_failed_images_total{job=\"$JOB\"}[$PERIOD])",
     "legendFormat": "Processed"
    }
   ]
  },
  {
   "title": "Conflictive names per  $PERIOD",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(yams_conflictive_name_total{job=\"$JOB\"}[$PERIOD])",
     "legendFormat": "Processed"
    }
   ]
  },
  {
   "title": "Duplicated per $PERIOD",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(yams_upload_duplicated_error_total{job=\"$JOB\"}[$PERIOD])",
     "legendFormat": "Processed"
    }
   ]
  }
 ]
}