version: '2'
services:
  postgres:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    stdin_open: true
    tty: true
    ports:
    - 7722:5432/tcp
    labels:
      io.rancher.container.pull_image: always
